import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./_components/Navbar";
import { cn } from "@/utils/cn";
import Providers from "./_components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={cn(
                "bg-white text-slate-900 antialiased",
                inter.className
            )}
        >
            <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
                <Providers>
                    {children}
                    <Navbar />
                </Providers>
                <div className="h-40 md:hidden" />
            </body>
        </html>
    );
}
